In [2]:
import pandas as pd
#used for datastructures and dataframes
path = "D:/TUTEDUDE/DateAnalysis/auto-mpg.csv"
#df=dataframe
df = pd.read_csv(path)
#df = pd.read_csv(path, headers = None)
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [3]:
df.head(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [4]:
df.tail(5)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [5]:
df.to_csv(path) #TO SAVE THE FILE

In [6]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [7]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [8]:
df.describe(include="all")

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [11]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [10]:
import pandas as pd
path = "D:/TUTEDUDE/DateAnalysis/data.xlsx"
df1=pd.read_excel(path)
print(df1)

    S. No.     A   B   C     D   E
0        1   2.0   1   5   3.0   4
1        2   4.0   3  10   6.0   8
2        3   6.0   5  15   9.0  12
3        4   8.0   7  20  12.0  16
4        5  10.0   9  25  15.0  20
5        6  12.0  11  30  18.0  24
6        7  14.0  13  35  21.0  28
7        8  16.0  15  40  24.0  32
8        9  18.0  17  45  27.0  36
9       10  20.0  19  50  30.0  40
10      11   NaN  21  55   NaN  44

In [12]:
df1.head(5)

   S. No.     A  B   C     D   E
0       1   2.0  1   5   3.0   4
1       2   4.0  3  10   6.0   8
2       3   6.0  5  15   9.0  12
3       4   8.0  7  20  12.0  16
4       5  10.0  9  25  15.0  20

In [13]:
headers=["S.No.","EVEN","ODD","Multiples 5", "Multiples 3", "Multiples 4"]
df1.columns=headers
df1.head(5)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0            4
1      2   4.0    3           10          6.0            8
2      3   6.0    5           15          9.0           12
3      4   8.0    7           20         12.0           16
4      5  10.0    9           25         15.0           20

In [14]:
print(df1)

    S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0       1   2.0    1            5          3.0            4
1       2   4.0    3           10          6.0            8
2       3   6.0    5           15          9.0           12
3       4   8.0    7           20         12.0           16
4       5  10.0    9           25         15.0           20
5       6  12.0   11           30         18.0           24
6       7  14.0   13           35         21.0           28
7       8  16.0   15           40         24.0           32
8       9  18.0   17           45         27.0           36
9      10  20.0   19           50         30.0           40
10     11   NaN   21           55          NaN           44

In [15]:
df1["ODD"]=df1["ODD"]+1
df1.head(5)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    2            5          3.0            4
1      2   4.0    4           10          6.0            8
2      3   6.0    6           15          9.0           12
3      4   8.0    8           20         12.0           16
4      5  10.0   10           25         15.0           20

In [16]:
df1["ODD"]=df1["ODD"]-1
df1.head(5)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0            4
1      2   4.0    3           10          6.0            8
2      3   6.0    5           15          9.0           12
3      4   8.0    7           20         12.0           16
4      5  10.0    9           25         15.0           20

In [17]:
print(df1)

    S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0       1   2.0    1            5          3.0            4
1       2   4.0    3           10          6.0            8
2       3   6.0    5           15          9.0           12
3       4   8.0    7           20         12.0           16
4       5  10.0    9           25         15.0           20
5       6  12.0   11           30         18.0           24
6       7  14.0   13           35         21.0           28
7       8  16.0   15           40         24.0           32
8       9  18.0   17           45         27.0           36
9      10  20.0   19           50         30.0           40
10     11   NaN   21           55          NaN           44

In [20]:
df1.drop([10],axis=0) #axis=1 is column and #axis=0 is a row.

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0            4
1      2   4.0    3           10          6.0            8
2      3   6.0    5           15          9.0           12
3      4   8.0    7           20         12.0           16
4      5  10.0    9           25         15.0           20
5      6  12.0   11           30         18.0           24
6      7  14.0   13           35         21.0           28
7      8  16.0   15           40         24.0           32
8      9  18.0   17           45         27.0           36
9     10  20.0   19           50         30.0           40

In [24]:
print(df1)

    S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0       1   2.0    1            5          3.0            4
1       2   4.0    3           10          6.0            8
2       3   6.0    5           15          9.0           12
3       4   8.0    7           20         12.0           16
4       5  10.0    9           25         15.0           20
5       6  12.0   11           30         18.0           24
6       7  14.0   13           35         21.0           28
7       8  16.0   15           40         24.0           32
8       9  18.0   17           45         27.0           36
9      10  20.0   19           50         30.0           40
10     11   NaN   21           55          NaN           44

In [22]:
df1.dropna()

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0            4
1      2   4.0    3           10          6.0            8
2      3   6.0    5           15          9.0           12
3      4   8.0    7           20         12.0           16
4      5  10.0    9           25         15.0           20
5      6  12.0   11           30         18.0           24
6      7  14.0   13           35         21.0           28
7      8  16.0   15           40         24.0           32
8      9  18.0   17           45         27.0           36
9     10  20.0   19           50         30.0           40

In [23]:
df1.dropna(subset = ["EVEN"],axis=0)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0            4
1      2   4.0    3           10          6.0            8
2      3   6.0    5           15          9.0           12
3      4   8.0    7           20         12.0           16
4      5  10.0    9           25         15.0           20
5      6  12.0   11           30         18.0           24
6      7  14.0   13           35         21.0           28
7      8  16.0   15           40         24.0           32
8      9  18.0   17           45         27.0           36
9     10  20.0   19           50         30.0           40

In [25]:
import numpy as np
df1["EVEN"].replace(np.nan,22)

0      2.0
1      4.0
2      6.0
3      8.0
4     10.0
5     12.0
6     14.0
7     16.0
8     18.0
9     20.0
10    22.0
Name: EVEN, dtype: float64

In [26]:
df1["Multiples 4"]=df1["Multiples 4"]/2

In [27]:
df1.head(5)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0          2.0
1      2   4.0    3           10          6.0          4.0
2      3   6.0    5           15          9.0          6.0
3      4   8.0    7           20         12.0          8.0
4      5  10.0    9           25         15.0         10.0

In [28]:
df1.rename(columns={"Multiples 4":"Multiples 2"})

    S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 2
0       1   2.0    1            5          3.0          2.0
1       2   4.0    3           10          6.0          4.0
2       3   6.0    5           15          9.0          6.0
3       4   8.0    7           20         12.0          8.0
4       5  10.0    9           25         15.0         10.0
5       6  12.0   11           30         18.0         12.0
6       7  14.0   13           35         21.0         14.0
7       8  16.0   15           40         24.0         16.0
8       9  18.0   17           45         27.0         18.0
9      10  20.0   19           50         30.0         20.0
10     11   NaN   21           55          NaN         22.0

In [29]:
df1.dtypes

S.No.            int64
EVEN           float64
ODD              int64
Multiples 5      int64
Multiples 3    float64
Multiples 4    float64
dtype: object

In [32]:
df1.drop([10],axis=0)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 4
0      1   2.0    1            5          3.0          2.0
1      2   4.0    3           10          6.0          4.0
2      3   6.0    5           15          9.0          6.0
3      4   8.0    7           20         12.0          8.0
4      5  10.0    9           25         15.0         10.0
5      6  12.0   11           30         18.0         12.0
6      7  14.0   13           35         21.0         14.0
7      8  16.0   15           40         24.0         16.0
8      9  18.0   17           45         27.0         18.0
9     10  20.0   19           50         30.0         20.0

In [33]:
df1.rename(columns={"Multiples 4":"Multiples 2"}, inplace = True)

In [35]:
df1.head(5)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 2
0      1   2.0    1            5          3.0          2.0
1      2   4.0    3           10          6.0          4.0
2      3   6.0    5           15          9.0          6.0
3      4   8.0    7           20         12.0          8.0
4      5  10.0    9           25         15.0         10.0

In [39]:
df1.dtypes

S.No.            int64
EVEN           float64
ODD              int64
Multiples 5      int64
Multiples 3    float64
Multiples 2    float64
dtype: object

f

In [43]:
df1["Multiples 2"]=df1["Multiples 2"].astype("int")

In [44]:
df1.dtypes

S.No.            int64
EVEN           float64
ODD              int64
Multiples 5      int64
Multiples 3    float64
Multiples 2      int32
dtype: object

In [45]:
df1.head(10)

   S.No.  EVEN  ODD  Multiples 5  Multiples 3  Multiples 2
0      1   2.0    1            5          3.0            2
1      2   4.0    3           10          6.0            4
2      3   6.0    5           15          9.0            6
3      4   8.0    7           20         12.0            8
4      5  10.0    9           25         15.0           10
5      6  12.0   11           30         18.0           12
6      7  14.0   13           35         21.0           14
7      8  16.0   15           40         24.0           16
8      9  18.0   17           45         27.0           18
9     10  20.0   19           50         30.0           20